# fly.toml app configuration file generated for serverregistro on 2023-06-08T20:03:12-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "serverregistro"
primary_region = "bog"

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
